config/routes.rb
RemarkerbeServer::Application.routes.draw do

  

  

  

  

  

  

  
  root :to => "home#index"
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  
  

  

  match '/auth/:provider/callback', to: 'notes#callback_sync'
  match '/auth/failure', to: 'notes#auth_fail'
  match '/logout', to: 'notes#logout'
  resources :notes do
    member do
    end

    collection do
      post :sync
      get :sync
      post :callback_sync
      post :test_cors
      get :test_cors
      get :logout
      get :auth_fail
    end
  end
  
  resources :upload do
    collection do 
      get :index
      post :upload
    end 
  end
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :url, :user_id, :title, :provider, :tags, :words, :username
  serialize :tags
  serialize :words
end

app/controllers/notes_controller.rb
# encoding: utf-8
#Encoding::default_internal = "utf-8"
#Encoding::default_external = "utf-8"
require 'encryptor'
require 'provider_factory.rb'
require 'provider/note_error'
$note_error_logger = Logger.new(Rails.root + "log/note_sync_error.log")  
$note_error_logger.formatter = proc { |severity, datetime, progname, msg|
    "#{datetime}: #{msg}\n"
  }
class NotesController < ApplicationController
  rescue_from Exception, :with => :log_error
  rescue_from AuthorizationException, :with => :process_authorize
  rescue_from SavingNoteException, :with => :process_saving_exception

  before_filter :get_authtoken_from_cookie, :only => :sync
  before_filter :process_params, :only => :sync
  before_filter :authenticate_user!, :only =>:show

  # POST /notes/sync
  def sync
    logger.info cookies.to_a
    logger.info session
    logger.info request.env['HTTP_USER_AGENT']
    @note = Note.create params[:note] 
    session[:note_id]= @note.id
    cookies[:note_id] = { :value => @note.id, :expires => 1.days.from_now.utc }
    logger.info @note.id
    raise AuthorizationException, "Not found cookie.Need init." if @authtoken.blank?
    # todo : wrong combination of token and provider
    @provider = cookies[:provider]
    callback_sync
  end

  def callback_sync
    logger.info cookies.to_a
    logger.info session
    logger.info params[:pid]
    @authtoken ||= request.env['omniauth.auth']['credentials']['token']
    @provider ||= (params[:endpoint] || "evernote")
    @is_cn = /zh-cn/i.match request.env["HTTP_ACCEPT_LANGUAGE"]
    logger.info @provider
    logger.info @authtoken
    cookies[:rmkb_token] = { :value => encrypt_authtoken(@authtoken), :expires => 1.years.from_now.utc }
    cookies[:provider] = { :value => @provider, :expires => 1.years.from_now.utc }
    note_id = session[:note_id] || cookies[:note_id] || params[:pid]
    logger.info note_id
    note = Note.find note_id
    create_note note
    save_user_info note
    reset_session
    render "_success"
  end

  def show
    @note = Note.find params[:id]
  end

  def logout 
    cookies.delete :rmkb_token
    cookies.delete :provider 
    render '_logout', :layout => false
  end

  def auth_fail
    msg = params[:message] || 'Session expired. Please try again.'
    msg = "Error! #{msg}"
    render :text => msg
  end
  private
  def  get_authtoken_from_cookie
    @authtoken = cookies[:rmkb_token]
    @authtoken = decrypt_authtoken @authtoken if @authtoken.present?
  end
  def process_params
    params[:note][:content] = CGI::unescapeHTML(params[:note][:content])
    params[:note][:tags] = JSON::load params[:note][:tags]
    params[:note][:words] = JSON::load params[:note][:words]
    params[:note][:provider] = "evernote"
  end
  def secret_key
    "$@#!%U^H%D#1&Pw&**".freeze
  end
  def encrypt_authtoken str
    Base64::encode64 Encryptor.encrypt(str, :key => secret_key)
  end
  def decrypt_authtoken str
    Encryptor.decrypt(Base64::decode64(str), :key => secret_key)
  end
  def save_user_info note
    info =  provider.get_user :authtoken => @authtoken
    note.username = info["username"]
    note.provider = @provider
    note.save
  end
  def create_note note
    provider.sync :authtoken => @authtoken, :content => note.content, :title => note.title, :url => note.url, :tags => note.tags
  end
  
  def provider
    ProviderFactory.choose(@provider || "evernote")
  end
  def process_authorize e
    log_error e, false
    cookies.delete :rmkb_token
    cookies.delete :provider 
    @message = { :status => 302, :url => "http://#{request.host_with_port}/auth/evernote", :base => "http://#{request.host_with_port}/auth/" }
    #@message = { :status => 302, :url => "http://#{request.host_with_port}/auth/evernote"}
    #@message = { :status => 302, :url => "http://#{request.host_with_port}/auth/yinxiang"}
    @is_cn = /zh-cn/i.match request.env["HTTP_ACCEPT_LANGUAGE"]
    render "_redirect", :layout => false
  end
  def process_saving_exception e
    log_error e, false
    render "_fail", :layout => false
  end
  def log_error e, raise_again = true
    $note_error_logger.error "===================================================="
    $note_error_logger.error session[:note_id]
    $note_error_logger.error e.inspect
    $note_error_logger.error e.message
    $note_error_logger.error e.backtrace[0..5]
    logger.error e.inspect
    logger.error e.message
    logger.error e.backtrace
    if raise_again
      render "_fail", :layout => false
    end
  end
  

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_fail.html.erb
<h2>Error</h2>
<p>We are sorry that some error occurs when saving to evernote. Please try again. If this error happens again, you should save it manually. </p>
<div id='export-html' style='display:none;'>
  <script>
    window.$M && $M.notify("Sorry that some error occurs. Please try again. If this happens again, you should save it manually.");
  </script>
</div>
<script>
  var _html = document.getElementById('export-html').innerHTML;
  window.parent.postMessage({
    status : "500",
    content : _html
  }, "*");
</script>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_logout.html.erb
<h2>登出成功!</h2>
<p>下次保存时，您将重新选择要认证同步的笔记服务.</p>

app/views/notes/_redirect.html.erb
<div id='export-html' style='display:none;'>
  <style>
    .remarkalbe-selector{
      margin-bottom:0 !important;
      padding:0 !important;
      text-align:left;
      margin-top:10px !important;
      <%if !@is_cn %>
      display:none !important;
      <%end%>
    }
    .remarkalbe-selector li{
      display:inline !important;
      font-size:14px !important;
      font-weight:bold !important;
      border:2px dashed #ccc !important;
      padding:4px !important;
      margin-right:6px !important;
      color:#ccc !important; 
      cursor:pointer !important;
    }
    .remarkalbe-selector li.rmkb-active{
      color:#fff !important;
      border:2px solid #fc288d !important;
      background: #FC288D !important;
    }
    .remarkalbe-info-box-buttons{
      text-align:left !important;
    }
    #rmkb-slide-for-chinese{
      padding-left:0px; 
      cursor:pointer;
    }
    #rmkb-slide-for-chinese::before{
      content: "\25ba";
    }
    #rmkb-slide-for-chinese.rmkb-active::before{
      content: "\2714";
    }
  </style>
  <script>
    var __not_evernote_user = "Not Evernote user?"
    <% if @is_cn %>
    __not_evernote_user = "Save manually?"
  <% end %>
   if (window.$M){
     $M.messageBox("Connect Evernote","Please authorize Remarkerbe with access to your <b>Evernote</b> account.<ul class='remarkalbe-selector'><li class='rmkb-active' provider='evernote?endpoint=yinxiang'>印象笔记</li><li provider='evernote'>Evernote International</li></ul>",[{"content" : "Go for authorization", "target" : "_blank", "href" : "javascript:void(0)", "class" : "rmkb-btn rmkb-sync" }, {"content" : __not_evernote_user, "target" : "_blank", "href" : ($M.site || "http://remarker.be/" )+ "getting_started#faq" } ])
    var _rmkb_active = "rmkb-active";
    var _rmkb_base = "<%= @message[:base] %>"
    var $label = $("p.remarkalbe-info-box-content > b");
    var $title = $("h3.remarkalbe-info-box-title");
    var _rmkb_auth_url = ''
    $M.support_save_opener = false
    if (!$M._redirect_code_loaded){
      $(document).on("mousedown", ".remarkalbe-selector li", function(){
        var $elem = $(this);
        $elem.addClass(_rmkb_active).siblings().removeClass(_rmkb_active);
        var endpoint = $elem.attr("provider");
        var url =  _rmkb_base + endpoint
        if (url.indexOf('?') > -1){
          url += "&"
        }else{
          url +="?"
        }
        url += "pid=<%= @note.id %>"
        if ($M.support_save_opener){
           _rmkb_auth_url = url;
        } else {
            $(".rmkb-sync").attr('href', url);
        }
        
        $label.text($elem.text());    
        $title.text("Connect " + $elem.text())
      })
      $(document).on("click", "#rmkb-slide-for-chinese", function(){
        $(this).toggleClass("rmkb-active").next(".remarkalbe-selector").toggle();
        if ($(this).is(".rmkb-active")){
          $label.text($("li[provider].rmkb-active").text());    
          }else{
          $("li[provider='evernote']").mousedown();
          $label.text("Evernote");
        }
      });
      if ($M.support_save_opener){
        $(document).on("click", ".rmkb-sync", function(){
            window.open(_rmkb_auth_url);
          })
      }
      $M._redirect_code_loaded = true;
    }
    <% if @is_cn %>
    $(".remarkalbe-selector li:eq(0)").mousedown();
    <% elsif %>
    $(".remarkalbe-selector li:eq(1)").html('Evernote').mousedown();
    <% end %>
    $(".rmkb-sync").click(function(){
      $M.saved = true;
    });
  }
  </script>
</div>
<script>
  var _html = document.getElementById('export-html').innerHTML;
  window.parent.postMessage({
    status : "302",
    content : _html
  }, "*");
</script>

app/views/notes/_success.html.erb
<h2>Done</h2>
<p>Save to Evernote successfully!</p>
<!--
<script>
  window.parent.postMessage({
    status : "200"
  }, "*");
</script>
-->
<div id='export-html' style='display:none;'>
  <style>
    @media (max-width:1080px){

      #remarkalbe-notify{
        text-align:left;
      }
    }
    #rmkb-for-chinese{
      position:absolute;
      top:7px;
      right:190px;
    }
  </style>
  <script>
    //setTimeout(function(){$M.notify('Save successfully!   | For Chinese user: 如果要切换Evernote/印象笔记，<a  href=\"<%= "http://#{request.host_with_port}/logout/" %>\"  target="_blank" style="text-decoration:underline;">请点此登出</a>.', null, false);}, 500);
    if (window.$M){
    setTimeout(function(){$M.notify('<span id="rmkb-success">Save successfully!</span><span id="rmkb-for-chinese">*For Chinese user: <a  href=\"<%= "http://#{request.host_with_port}/logout/" %>\"  target="_blank" style="text-decoration:underline;">切换Evernote/印象笔记</a>?</span>', null, false);}, 500);
    $M.saved = true;
    if ($M.in_readable){
      window.parent.$M.saved = true;
    }
  }
  </script>
</div>
<script>
  var _html = document.getElementById('export-html').innerHTML;
  if (window.parent == window){
      window.opener.postMessage('saved', '*')
      window.close()
    } else {
    window.parent.postMessage({
      status : "302",
      content : _html
    }, "*");
  }
</script>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <tr>
    <th>User</th>
    <th>Url</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notes.each do |note| %>
  <tr>
    <td><%= note.user_id %></td>
    <td><%= note.url %></td>
    <td><%= note.content %></td>
    <td><%= link_to 'Show', note %></td>
    <td><%= link_to 'Edit', edit_note_path(note) %></td>
    <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<div style='background:#eee;color:#666;font-size:14px;padding:4px 10px; border-radius:4px'>
<p>
  <b>User:</b>
  <%= @note.username %>
</p>

<p>
  <b>Url:</b>
  <a href="<%= @note.url %>" target='_blank'>"<%= @note.url %>"</a>
  </p>
</div>

<%=raw @note.content %>